version: "3.8"

services:
  build:
    image: cardano-builder:1.12.0
    build:
      context: .
      target: cardano-builder

  bins:
    image: cardano-bins:1.12.0
    build:
      context: .
      target: cardano-bins
